name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  windows-msys2:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: CLANG64, env: clang-x86_64, build: Release }

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup ${{ matrix.sys }}
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.sys }}
          install: >-
            base-devel
            mingw-w64-${{ matrix.env }}-toolchain
            mingw-w64-${{ matrix.env }}-cmake
            mingw-w64-${{ matrix.env }}-openblas

      - name: Build using CMake w/ OpenBLAS
        shell: msys2 {0}
        run: |
          git submodule sync && git submodule update --init --recursive
          cmake -B build -DGGML_OPENBLAS=ON
          cmake --build build --config ${{ matrix.build }} -j $(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: build
          if-no-files-found: error
          retention-days: 89
          compression-level: 0
          overwrite: true
          include-hidden-files: false
